version: "2"

services:
  zookeeper:
    image: ubuntu/zookeeper
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: ubuntu/kafka
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"

#  api-service:
#    build:
#      context: ./
#      dockerfile: dockerfiles/api.Dockerfile
#    hostname: master
#    container_name: master
#    ports:
#      - "8081:8081"
#    volumes:
#      - "./api-service/build/libs:/service"

  calculator-service:
    build:
      context: ./
      dockerfile: ./dockerfiles/calculator.Dockerfile
    container_name: worker
    volumes:
      - "./calculator-service/build/libs:/service"
