version: "3"

services:
    zookeeper:
        image: ubuntu/zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"

    kafka:
        image: ubuntu/kafka
        depends_on:
            - zookeeper
        hostname: kafka
        ports:
            - "9092:9092"

    api-service:
        image: smf/api-service
        build:
            context: ./
            dockerfile: dockerfiles/api.Dockerfile
        depends_on:
            - kafka
        hostname: localhost
        ports:
            - "8081:8081"
        volumes:
            - "./api-service/build/libs:/service"
            - "//var/run/docker.sock:/var/run/docker.sock"

    calculator-service:
        image: smf/calculator-service
        build:
            context: ./
            dockerfile: ./dockerfiles/calculator.Dockerfile
        depends_on:
            - kafka
        volumes:
            - "./calculator-service/build/libs:/service"
        deploy:
            replicas: 10
